# Generated by Django 5.0.3 on 2024-05-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wos', '0002_alter_productcategory_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleReference', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('UnitPriceHT', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Packaging', models.CharField(choices=[('ContainerizedProduct', 'produit conteneurisé'), ('NoneContainerizedProduct', 'produit en vrac')], max_length=30)),
                ('Amount', models.FloatField()),
                ('ProductCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wos.productcategory')),
            ],
        ),
    ]
